"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Brain,
  TrendingUp,
  Building2,
  Cpu,
  Lightbulb,
  AlertTriangle,
  Loader2,
  Calendar,
  BarChart3,
  RefreshCw,
  Copy,
  Download,
  Check,
  Clock,
} from "lucide-react"
import { toast } from "sonner"

interface ExecutiveBriefing {
  executiveSummary: string
  macroTrends: Array<{ trend: string; evidence: string; implication: string }>
  keyDevelopments: Array<{ development: string; significance: string }>
  companiesInFocus: Array<{ name: string; context: string }>
  technologiesInFocus: Array<{ name: string; context: string }>
  strategicInsights: string[]
  emergingPatterns: string[]
}

interface SummaryResponse {
  success: boolean
  period: { days: number; startDate: string; endDate: string }
  analysisCount: number
  executiveBriefing: ExecutiveBriefing
  usage: { inputTokens: number; outputTokens: number }
  error?: string
  generatedAt?: string
}

export default function AnalysisPage() {
  const [days, setDays] = useState("7")
  const [isLoading, setIsLoading] = useState(false)
  const [isLoadingInitial, setIsLoadingInitial] = useState(true)
  const [summary, setSummary] = useState<SummaryResponse | null>(null)
  const [copied, setCopied] = useState(false)

  // Load saved summary from database on mount
  useEffect(() => {
    const loadBriefing = async () => {
      try {
        const res = await fetch("/api/briefings")
        const data = await res.json()
        if (data.briefing) {
          setSummary(data.briefing)
        }
      } catch (e) {
        console.error("Failed to load saved briefing:", e)
      } finally {
        setIsLoadingInitial(false)
      }
    }
    loadBriefing()
  }, [])

  // Generate markdown from the briefing
  const generateMarkdown = (data: SummaryResponse): string => {
    const b = data.executiveBriefing
    const lines: string[] = []
    const generatedDate = data.generatedAt ? new Date(data.generatedAt) : new Date()

    lines.push(`# Executive Briefing`)
    lines.push(``)
    lines.push(`**Generated:** ${generatedDate.toLocaleString()}`)
    lines.push(`**Period:** ${new Date(data.period.startDate).toLocaleDateString()} - ${new Date(data.period.endDate).toLocaleDateString()}`)
    lines.push(`**Analyses:** ${data.analysisCount}`)
    lines.push(``)

    if (b.executiveSummary) {
      lines.push(`## Executive Summary`)
      lines.push(``)
      lines.push(b.executiveSummary)
      lines.push(``)
    }

    if (b.macroTrends?.length > 0) {
      lines.push(`## Macro Trends`)
      lines.push(``)
      b.macroTrends.forEach((t) => {
        lines.push(`### ${t.trend}`)
        lines.push(``)
        lines.push(`**Evidence:** ${t.evidence}`)
        lines.push(``)
        lines.push(`**Implication:** ${t.implication}`)
        lines.push(``)
      })
    }

    if (b.keyDevelopments?.length > 0) {
      lines.push(`## Key Developments`)
      lines.push(``)
      b.keyDevelopments.forEach((d) => {
        lines.push(`### ${d.development}`)
        lines.push(``)
        lines.push(d.significance)
        lines.push(``)
      })
    }

    if (b.companiesInFocus?.length > 0) {
      lines.push(`## Companies in Focus`)
      lines.push(``)
      b.companiesInFocus.forEach((c) => {
        lines.push(`- **${c.name}:** ${c.context}`)
      })
      lines.push(``)
    }

    if (b.technologiesInFocus?.length > 0) {
      lines.push(`## Technologies in Focus`)
      lines.push(``)
      b.technologiesInFocus.forEach((t) => {
        lines.push(`- **${t.name}:** ${t.context}`)
      })
      lines.push(``)
    }

    if (b.strategicInsights?.length > 0) {
      lines.push(`## Strategic Insights`)
      lines.push(``)
      b.strategicInsights.forEach((s) => {
        lines.push(`- ${s}`)
      })
      lines.push(``)
    }

    if (b.emergingPatterns?.length > 0) {
      lines.push(`## Emerging Patterns`)
      lines.push(``)
      b.emergingPatterns.forEach((p) => {
        lines.push(`- ${p}`)
      })
      lines.push(``)
    }

    lines.push(`---`)
    lines.push(`*Generated by Disruption Intel on ${new Date().toLocaleDateString()}*`)

    return lines.join('\n')
  }

  const copyToClipboard = async () => {
    if (!summary) return
    const markdown = generateMarkdown(summary)
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    toast.success("Copied to clipboard")
    setTimeout(() => setCopied(false), 2000)
  }

  const exportToFile = () => {
    if (!summary) return
    const markdown = generateMarkdown(summary)
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    const dateStr = new Date().toISOString().split('T')[0]
    a.href = url
    a.download = `executive-briefing-${dateStr}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("Briefing exported")
  }

  const generateSummary = async () => {
    setIsLoading(true)

    try {
      const res = await fetch("/api/analysis/summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ days: parseInt(days) }),
      })

      const data = await res.json()

      if (data.success) {
        // Add timestamp
        const summaryWithTimestamp = {
          ...data,
          generatedAt: new Date().toISOString(),
        }
        setSummary(summaryWithTimestamp)

        // Save to database
        await fetch("/api/briefings", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            period: data.period,
            analysisCount: data.analysisCount,
            executiveBriefing: data.executiveBriefing,
            usage: data.usage,
          }),
        })

        toast.success("Executive briefing generated and saved")
      } else {
        toast.error(data.error || "Failed to generate summary")
      }
    } catch (error) {
      console.error("Failed to generate summary:", error)
      toast.error("Failed to generate summary")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Analysis Summary</h1>
          <p className="text-muted-foreground">
            Generate executive briefings from your analyzed content
          </p>
        </div>
      </div>

      {/* Controls */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <Calendar className="h-5 w-5" />
            Generate Executive Briefing
          </CardTitle>
          <CardDescription>
            Synthesize all analyses from a time period into macro trends and insights
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">Time period:</span>
              <Select value={days} onValueChange={setDays}>
                <SelectTrigger className="w-[180px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="7">Last 7 days</SelectItem>
                  <SelectItem value="14">Last 14 days</SelectItem>
                  <SelectItem value="30">Last 30 days</SelectItem>
                  <SelectItem value="60">Last 60 days</SelectItem>
                  <SelectItem value="90">Last 90 days</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button onClick={generateSummary} disabled={isLoading}>
              {isLoading ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Brain className="h-4 w-4 mr-2" />
                  Generate Briefing
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Loading State */}
      {isLoading && (
        <div className="space-y-4">
          <Skeleton className="h-40" />
          <div className="grid gap-4 md:grid-cols-2">
            <Skeleton className="h-60" />
            <Skeleton className="h-60" />
          </div>
        </div>
      )}

      {/* Results */}
      {summary?.success && summary.executiveBriefing && (
        <div className="space-y-6">
          {/* Stats Bar with Actions */}
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-4 text-sm text-muted-foreground flex-wrap">
              {summary.generatedAt && (
                <Badge variant="secondary" className="gap-1">
                  <Clock className="h-3 w-3" />
                  Generated: {new Date(summary.generatedAt).toLocaleString()}
                </Badge>
              )}
              <Badge variant="outline" className="gap-1">
                <BarChart3 className="h-3 w-3" />
                {summary.analysisCount} analyses
              </Badge>
              <span>
                Period: {new Date(summary.period.startDate).toLocaleDateString()} - {new Date(summary.period.endDate).toLocaleDateString()}
              </span>
              <span>
                Tokens: {summary.usage.inputTokens.toLocaleString()} in / {summary.usage.outputTokens.toLocaleString()} out
              </span>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={copyToClipboard}>
                {copied ? (
                  <Check className="h-4 w-4 mr-2 text-green-500" />
                ) : (
                  <Copy className="h-4 w-4 mr-2" />
                )}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button variant="outline" size="sm" onClick={exportToFile}>
                <Download className="h-4 w-4 mr-2" />
                Export .md
              </Button>
            </div>
          </div>

          {/* Executive Summary */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-xl">
                <Brain className="h-6 w-6 text-primary" />
                Executive Summary
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="prose prose-lg dark:prose-invert max-w-none">
                {summary.executiveBriefing.executiveSummary?.split('\n').map((p, i) => (
                  <p key={i} className="text-base leading-relaxed">{p}</p>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Macro Trends */}
          {summary.executiveBriefing.macroTrends?.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <TrendingUp className="h-6 w-6 text-green-500" />
                  Macro Trends
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {summary.executiveBriefing.macroTrends.map((trend, i) => (
                    <div key={i} className="p-5 rounded-lg border bg-card">
                      <h4 className="font-semibold text-primary text-lg mb-3">{trend.trend}</h4>
                      <p className="text-base text-muted-foreground mb-3 leading-relaxed">
                        <span className="font-medium">Evidence:</span> {trend.evidence}
                      </p>
                      <p className="text-base leading-relaxed">
                        <span className="font-medium">Implication:</span> {trend.implication}
                      </p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Key Developments */}
          {summary.executiveBriefing.keyDevelopments?.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <Lightbulb className="h-6 w-6 text-yellow-500" />
                  Key Developments
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {summary.executiveBriefing.keyDevelopments.map((dev, i) => (
                    <div key={i} className="flex gap-3 p-4 rounded-lg border">
                      <div className="flex-1">
                        <p className="font-medium text-base">{dev.development}</p>
                        <p className="text-base text-muted-foreground mt-2 leading-relaxed">{dev.significance}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Companies & Technologies */}
          <div className="grid gap-6 md:grid-cols-2">
            {summary.executiveBriefing.companiesInFocus?.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-xl">
                    <Building2 className="h-6 w-6 text-blue-500" />
                    Companies in Focus
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {summary.executiveBriefing.companiesInFocus.map((company, i) => (
                      <div key={i} className="flex items-start gap-3">
                        <Badge variant="secondary" className="text-sm">{company.name}</Badge>
                        <span className="text-base text-muted-foreground leading-relaxed">{company.context}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {summary.executiveBriefing.technologiesInFocus?.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-xl">
                    <Cpu className="h-6 w-6 text-purple-500" />
                    Technologies in Focus
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {summary.executiveBriefing.technologiesInFocus.map((tech, i) => (
                      <div key={i} className="flex items-start gap-3">
                        <Badge variant="outline" className="text-sm">{tech.name}</Badge>
                        <span className="text-base text-muted-foreground leading-relaxed">{tech.context}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </div>

          {/* Strategic Insights & Emerging Patterns */}
          <div className="grid gap-6 md:grid-cols-2">
            {summary.executiveBriefing.strategicInsights?.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-xl">
                    <TrendingUp className="h-6 w-6 text-emerald-500" />
                    Strategic Insights
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-3">
                    {summary.executiveBriefing.strategicInsights.map((insight, i) => (
                      <li key={i} className="flex items-start gap-3 text-base leading-relaxed">
                        <span className="text-primary mt-1">•</span>
                        {insight}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            )}

            {summary.executiveBriefing.emergingPatterns?.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-xl">
                    <AlertTriangle className="h-6 w-6 text-amber-500" />
                    Emerging Patterns
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-3">
                    {summary.executiveBriefing.emergingPatterns.map((pattern, i) => (
                      <li key={i} className="flex items-start gap-3 text-base leading-relaxed">
                        <span className="text-amber-500 mt-1">•</span>
                        {pattern}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            )}
          </div>

          {/* Regenerate Button */}
          <div className="flex justify-center">
            <Button variant="outline" onClick={generateSummary} disabled={isLoading}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Regenerate Briefing
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
